### ISSUE TITLE
NDVI DN/Radiance/TOA?? question

### ISSUE THREAD

**Issue by cappelaere** [developmentseed/landsat-util#192]
When you process NDVI, are you really using the digital numbers from bands 4 and 5 rather than use spectral radiance, or even better, TOA reflectance so we can compare NDVI's across different scenes?
Just wondering.
[I guess the question would be the same for RGB]
Many thanks.
Pat.

**Comment by matthewhanson** [comment]
Hi Pat, 

Yes, it's a serious deficiency in the current landsat-util, which is currently only for visual use.  Even using spectral radiance would be inadequate for inter-scene comparison, over different time periods because of  varying solar irradiance and geometries. 

A new version of landsat-util is in the works and will base products off of TOA instead, look for that in the next couple months.

Thanks for the feedback!

**Comment by cappelaere** [comment]
Hi Matthew,

This is what I thought. No problem.  Thanks for quick response.
I will work on that here… I have some code lying around...  I need at least TOA NDVI (surface reflectance would even be better) to co-register some of our EO-1 scenes that have been affected by a clock drift issue that USGS cannot correct.
I know that you can order that new NDVI SR product from USGS ESPA but it takes 3-5 hours to receive and it is hard to automate.

Pat Cappelaere
pat@cappelaere.com

Cell: 410 340 4868
Skype: patrice_cappelaere
gmail: cappelaere@gmail.com

**Comment by matthewhanson** [comment]
Hi Pat - yes, the SR product is not easy to automatically get, as it still requires using Earth Explorer to request them.
FYI, you might already know this stuff, but in case it helps...

For Landsat7 and earlier you had to use the gain and offset to convert from DN to radiance, then apply supplied band coefficients to convert to TOA along with some calculations involving the earth-sun distance, you can see an example here:

https://github.com/gipit/gips/blob/master/gips/data/landsat/landsat.py#L330

But with Landsat8 there are gains and offsets supplied in the MTL file to convert directly from DN to TOA.

Also, note that atm corrected ref will lead to slightly higher NDVI values overall since there is a greater attenuation in the red than in nir.

**Comment by cappelaere** [comment]
Hi Matt,

You may already know this but to compute L8 TOA, I do not think that there is much to change to the code base.

in image.py / _read_metdata
	you may need to get some additional parameters

	REFLECTANCE_MULT_BAND_4
	REFLECTANCE_MULT_BAND_5
	REFLECTANCE_ADD_BAND_4
	REFLECTANCE_ADD_BAND_5
	SUN_ELEVATION

def toa(bandNum, metadata):
	dn_data		= get_band_data(bandNum)		
	
	mp 			= float(metadata['REFLECTANCE_MULT_BAND_'+str(bandNum)])
	ap			= float(metadata['REFLECTANCE_ADD_BAND_'+str(bandNum)])
	se			= float(metadata['SUN_ELEVATION'])
	
	toa			= (mp * dn_data + ap) / math.sin( se * math.pi/180.0)
	return toa


Pat Cappelaere
pat@cappelaere.com

Cell: 410 340 4868
Skype: patrice_cappelaere
gmail: cappelaere@gmail.com

**Comment by matthewhanson** [comment]
@cappelaere landsat-util will be deprecated in favor of using our new [sat-api](https://medium.com/devseed/sat-api-an-api-for-spatiotemporal-asset-catalogs-88c3c78fdb0e) and [sat-search](https://github.com/sat-utils/sat-search/). The processing functionality of landsat-util will be replaced with a new version of [sat-process](https://github.com/sat-utils/sat-process).

I'm not sure how we'll include the ability to calculate TOA reflectance. I'd like to, but it may become a moot point as USGS is working on a new Analysis Ready dataset that will provide the data as surface reflectance.
