### ISSUE TITLE
Process is eating up all the space on my SSD

### ISSUE THREAD

**Issue by szmarci** [developmentseed/landsat-util#30]
Yesterday I tried to get some satellite imagery from Landsat-8 using your utility, but the process stopped because I ran out of free space on my SSD. I started with about 20 GB of free space (I'm on a Mac, 10.10, 6 GB of ram) but after a while it stopped. I had the final image in the `~/landsat` folder (about 200 MB), I opened it, it seems fine nothing interesting. But the process in the terminal was still running, although it seemed pretty much dead, so eventually I quit it.
So the image seems to be okay, but most of my free space has gone.
I checked `/private/var/folders/_3/67r5_rl53y99y3sxth7bk95m0000gn/T/` where I found two tmp***** folders full of TIF satellite images, taking up approx. 16 GB of space. After several shutdown/restart they are till there.
I assume they are supposed to be deleted after completion, right? Maybe because the process never finished normally, they ended up undeleted.
What went wrong? Is it safe to remove them by hand?

**Comment by scisco** [comment]
Yes, it is safe to delete all landsat tmp files. Landsat generates a lot of temporary files that are deleted at the end of the process. However, if the process abruptly ends due to an error, the temp files remain in your `tmp` folder. 

BTW, we are working on this issue in the new version of landsat and hopefully when we release it smaller temp files are generated.

**Comment by szmarci** [comment]
Thanks! It is weird but after a couple of days the files were removed automatically.
