### ISSUE TITLE
GeoJSON output for landsat-search

### ISSUE THREAD

**Issue by sgillies** [developmentseed/landsat-util#68]
Being able to `landsat search <params> --geojson | geojsonio` and get a map showing footprints could be handy at times. It would require either including the [WRS databases](http://landsat.usgs.gov/tools_wrs-2_shapefile.php) as module data or setting up an API to serve path/row footprints. I'm happy to work on this if you like the idea.

**Comment by drewbo** [comment]
Instead of using the WRS database, we can grab from [landsat-api](https://github.com/developmentseed/landsat-api) which does serve up the path boundaries but they aren't exposed in landsat-util (selected attributes are grabbed [here](https://github.com/developmentseed/landsat-util/blob/master/landsat/search.py#L79-85)).

[Example API response](https://api.developmentseed.org/landsat?search)

I won't speak for @scisco but I think this is a cool idea.

**Comment by scisco** [comment]
@sgillies I love the idea too. We did use the WRS databases in the previous version for extracting country rows and paths. The code is [here](https://github.com/developmentseed/landsat-util/blob/835b91fbb24ea46356a7643b22ef516dd208aea8/landsat/clipper_helper.py).

However, we decided to scrap the feature in version 0.5 to lighten the dependencies. Rewriting the feature in Python would be a great addition.

**Comment by albert-decatur** [comment]
@drewbo this [gist](https://gist.github.com/albert-decatur/6b4582c19979bf25fd3f) has an example of grabbing corner lat/lon from the landsat-api to show scene extent on geojson.io

It's close to what it should be but imperfect, as you can see in the screenshots.
